# Generated by Django 5.2 on 2025-05-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0004_initial"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assignmentstudent",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="assignmentstudent",
            name="intake",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="student.intake",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentstudent",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="student.student"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignmentstudent",
            unique_together={("assignment", "student", "intake")},
        ),
    ]
