# Generated by Django 5.2 on 2025-05-06 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0005_alter_assignmentstudent_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentstudent",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_students",
                to="assignments.assignment",
            ),
        ),
    ]
