# Generated by Django 5.2 on 2025-05-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0005_alter_assignmentstudent_unique_together_and_more"),
        ("student", "0001_initial"),
        ("submission", "0001_initial"),
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="intake",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="student.intake",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracks.track",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignmentsubmission",
            unique_together={("assignment", "student", "intake")},
        ),
    ]
